# Generated by Django 4.1.1 on 2022-09-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_order_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.PositiveIntegerField(default=20000),
            preserve_default=False,
        ),
    ]
